# Generated by Django 5.1.7 on 2025-03-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('date_of_birth', models.DateField(default=0)),
                ('name', models.CharField(default=0, max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('customerid', models.IntegerField(default=0, primary_key='customerid', serialize=False)),
                ('accountdetails', models.CharField(default=0, max_length=70)),
            ],
        ),
    ]
